In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train_df = pd.read_excel('Data_Train.xlsx')

test_df = pd.read_excel('Test_set.xlsx')

In [3]:
final_df = pd.concat([train_df,test_df],ignore_index=True)
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [4]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Date_of_Journey  13354 non-null  str
 2   Source           13354 non-null  str
 3   Destination      13354 non-null  str
 4   Route            13353 non-null  str
 5   Dep_Time         13354 non-null  str
 6   Arrival_Time     13354 non-null  str
 7   Duration         13354 non-null  str
 8   Total_Stops      13353 non-null  str
 9   Additional_Info  13354 non-null  str
 10  Price            10683 non-null  float64
dtypes: float64(1), str(10)
memory usage: 1.1 MB

# Feature Engineering 
# date Dtype = str,  to dd, mm, yyyy

In [5]:
#final_df['Date'] = final_df['Date_of_Journey'].str.split('/').str[0]
#final_df['Month'] = final_df['Date_of_Journey'].str.split('/').str[1]
#final_df['Year'] = final_df['Date_of_Journey'].str.split('/').str[2]

In [6]:
final_df['Date'] = final_df['Date_of_Journey'].apply(lambda x:x.split('/')[0])
final_df['Month'] = final_df['Date_of_Journey'].apply(lambda x:x.split('/')[1])
final_df['Year'] = final_df['Date_of_Journey'].apply(lambda x:x.split('/')[2])
final_df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019

In [7]:
final_df['Date'] = final_df['Date'].astype(int)
final_df['Month'] = final_df['Month'].astype(int)
final_df['Year'] = final_df['Year'].astype(int)
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Date_of_Journey  13354 non-null  str
 2   Source           13354 non-null  str
 3   Destination      13354 non-null  str
 4   Route            13353 non-null  str
 5   Dep_Time         13354 non-null  str
 6   Arrival_Time     13354 non-null  str
 7   Duration         13354 non-null  str
 8   Total_Stops      13353 non-null  str
 9   Additional_Info  13354 non-null  str
 10  Price            10683 non-null  float64
 11  Date             13354 non-null  int64
 12  Month            13354 non-null  int64
 13  Year             13354 non-null  int64
dtypes: float64(1), int64(3), str(10)
memory usage: 1.4 MB

In [8]:
final_df.drop('Date_of_Journey',axis=1,inplace=True)

In [9]:
final_df.head(10)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019
5,SpiceJet,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873.0,24,6,2019
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270.0,1,3,2019
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625.0,27,5,2019

In [10]:
final_df['Arrival_Time'] = final_df['Arrival_Time'].str.split(' ').str[0]

In [11]:
final_df.isnull().sum()

Airline               0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
Date                  0
Month                 0
Year                  0
dtype: int64

In [12]:
final_df['Arrival_Hour'] = final_df['Arrival_Time'].apply(lambda x:x.split(':')[0])
final_df['Arrival_Min'] = final_df['Arrival_Time'].apply(lambda x:x.split(':')[1])

In [13]:
final_df.drop('Arrival_Time',axis=1,inplace=True)

In [14]:
final_df['Arrival_Hour'] = final_df['Arrival_Hour'].astype(int)
final_df['Arrival_Min'] = final_df['Arrival_Min'].astype(int)

In [15]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Dep_Time         13354 non-null  str
 5   Duration         13354 non-null  str
 6   Total_Stops      13353 non-null  str
 7   Additional_Info  13354 non-null  str
 8   Price            10683 non-null  float64
 9   Date             13354 non-null  int64
 10  Month            13354 non-null  int64
 11  Year             13354 non-null  int64
 12  Arrival_Hour     13354 non-null  int64
 13  Arrival_Min      13354 non-null  int64
dtypes: float64(1), int64(5), str(8)
memory usage: 1.4 MB

In [16]:
final_df['Dep_Time'] = final_df['Dep_Time'].str.split(' ').str[0] #Fetch only time exclude date
final_df['Dep_Hour'] = final_df['Dep_Time'].apply(lambda x:x.split(':')[0])
final_df['Dep_Min'] = final_df['Dep_Time'].apply(lambda x:x.split(':')[1])
final_df.drop('Dep_Time',axis=1,inplace=True)
final_df['Dep_Hour'] = final_df['Dep_Hour'].astype(int)
final_df['Dep_Min'] = final_df['Dep_Min'].astype(int)
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  str
 1   Source           13354 non-null  str
 2   Destination      13354 non-null  str
 3   Route            13353 non-null  str
 4   Duration         13354 non-null  str
 5   Total_Stops      13353 non-null  str
 6   Additional_Info  13354 non-null  str
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int64
 9   Month            13354 non-null  int64
 10  Year             13354 non-null  int64
 11  Arrival_Hour     13354 non-null  int64
 12  Arrival_Min      13354 non-null  int64
 13  Dep_Hour         13354 non-null  int64
 14  Dep_Min          13354 non-null  int64
dtypes: float64(1), int64(7), str(7)
memory usage: 1.5 MB

In [17]:
final_df.head(10)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35,16,50
5,SpiceJet,Kolkata,Banglore,CCU → BLR,2h 25m,non-stop,No info,3873.0,24,6,2019,11,25,9,0
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,15h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25,18,55
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,21h 5m,1 stop,No info,22270.0,1,3,2019,5,5,8,0
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,25h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25,8,55
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,7h 50m,1 stop,No info,8625.0,27,5,2019,19,15,11,25

In [18]:
final_df['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [19]:
final_df['Total_Stops'] = final_df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4})

In [20]:
final_df['Total_Stops'] = final_df['Total_Stops'].fillna(1).astype(int)

In [21]:
final_df.drop('Route',axis=1,inplace=True)

In [22]:
set(final_df['Additional_Info'])

{'1 Long layover',
 '1 Short layover',
 '2 Long layover',
 'Business class',
 'Change airports',
 'In-flight meal not included',
 'No Info',
 'No check-in baggage included',
 'No info',
 'Red-eye flight'}

In [23]:
final_df.head(2)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,2h 50m,0,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2,No info,7662.0,1,5,2019,13,15,5,50

In [24]:
final_df['Duration'] = (
    final_df['Duration']
    .str.extract(r'(?:(\d+)h)?\s*(?:(\d+)m)?')
    .fillna(0)
    .astype(int)
    .dot([60, 1])
)

In [33]:
set(final_df['Airline'])

{'Air Asia',
 'Air India',
 'GoAir',
 'IndiGo',
 'Jet Airways',
 'Jet Airways Business',
 'Multiple carriers',
 'Multiple carriers Premium economy',
 'SpiceJet',
 'Trujet',
 'Vistara',
 'Vistara Premium economy'}

In [36]:
from sklearn.preprocessing import LabelEncoder
lab_enc = LabelEncoder()

In [37]:
final_df['Airline'] = lab_enc.fit_transform(final_df['Airline'])
final_df['Source'] = lab_enc.fit_transform(final_df['Source'])
final_df['Destination'] = lab_enc.fit_transform(final_df['Destination'])
final_df['Additional_Info'] = lab_enc.fit_transform(final_df['Additional_Info'])

In [38]:
final_df.shape

(13354, 14)

In [39]:
final_df.head(2)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min
0,3,0,5,170,0,8,3897.0,24,3,2019,1,10,22,20
1,1,3,0,445,2,8,7662.0,1,5,2019,13,15,5,50

In [46]:
df = pd.get_dummies(final_df, columns=['Airline','Source','Destination','Additional_Info'],drop_first=True)
df

,Duration,Total_Stops,Price,Date,Month,Year,Arrival_Hour,Arrival_Min,Dep_Hour,Dep_Min,...,Destination_5,Additional_Info_1,Additional_Info_2,Additional_Info_3,Additional_Info_4,Additional_Info_5,Additional_Info_6,Additional_Info_7,Additional_Info_8,Additional_Info_9
0,170,0,3897.0,24,3,2019,1,10,22,20,...,True,False,False,False,False,False,False,False,True,False
1,445,2,7662.0,1,5,2019,13,15,5,50,...,False,False,False,False,False,False,False,False,True,False
2,1140,2,13882.0,9,6,2019,4,25,9,25,...,False,False,False,False,False,False,False,False,True,False
3,325,1,6218.0,12,5,2019,23,30,18,5,...,False,False,False,False,False,False,False,False,True,False
4,285,1,13302.0,1,3,2019,21,35,16,50,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,1435,1,NaN,6,6,2019,20,25,20,30,...,False,False,False,False,False,False,False,False,True,False
13350,155,0,NaN,27,3,2019,16,55,14,20,...,False,False,False,False,False,False,False,False,True,False
13351,395,1,NaN,6,3,2019,4,25,21,50,...,False,False,False,False,False,False,False,False,True,False
13352,915,1,NaN,6,3,2019,19,15,4,0,...,False,False,False,False,False,False,False,False,True,False
13353,860,1,NaN,15,6,2019,19,15,4,55,...,False,False,False,False,False,False,False,False,True,False

# data preprocessing and feature engineering is performed
# data cleaned for model learning